// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "harrish-webapp-bucket-env",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1paptall61lrp.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:207911b0-7d89-4555-bc20-61ebd822b7fc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5kWblnfkB",
    "aws_user_pools_web_client_id": "b887ec8d3pgep5jop9f06v8bg",
    "oauth": {}
};


export default awsmobile;
